# Generated by Django 4.2 on 2023-06-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container_management', '0003_alter_container_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='container_management.image'),
        ),
    ]
