# Generated by Django 4.2 on 2023-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container_management', '0004_alter_container_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='cpu_share',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='container',
            name='memory_limit',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
