# Generated by Django 4.2 on 2023-06-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container_management', '0006_dockerimage_alter_container_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='container_management.dockerimage'),
        ),
    ]
